name: Hackathon Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check files
      run: ls

    - name: Pipeline Success
      run: echo "Build successful 🎉"